server:
  port: 8761
#spring:
#  security:
#    user:
#      name: eureka
#      password: eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
spring:
  devtools:
    add-properties: false

